---
- name: Install Fail2ban
  package:
    name: fail2ban
    state: present

- name: Ensure Fail2ban is enabled and running
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure Fail2ban jail
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 1h
      findtime = 10m
      maxretry = 5
      backend = systemd

      [sshd]
      enabled = true
      logpath = %(sshd_log)s

- name: Configure Fail2ban filter for SSH
  copy:
    dest: /etc/fail2ban/filter.d/sshd.conf
    content: |
      [Definition]
      failregex = ^%(__prefix_line)sFailed password for .* from <HOST> port \d+ ssh2$
      ignoreregex = ^%(__prefix_line)sAccepted password for .* from <HOST> port \d+ ssh2$

- name: Restart Fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes
